module.exports = {
  "what is your name": "I am your friendly voice assistant.",
  "how are you": "I'm just a bunch of code, but I'm doing great!",
  "what can you do": "I can answer questions, tell jokes, and keep you company.",
  "tell me a joke": "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "what is the capital of india": "The capital of India is New Delhi.",
  "who is the president of india": "As of 2024, the President of India is Droupadi Murmu.",
  "who is the prime minister of india": "Narendra Modi is the Prime Minister of India.",
  "what is the national sport of india": "India does not have an officially declared national sport.",
  "what is the population of india": "India has a population of over 1.4 billion people.",
  "who won the last cricket world cup": "England won the 2019 Cricket World Cup.",
  "what is cricket": "Cricket is a bat-and-ball game played between two teams of eleven players.",
  "who is virat kohli": "Virat Kohli is a famous Indian cricketer.",
  "who is ms dhoni": "Mahendra Singh Dhoni is a former Indian cricket captain and a legend.",
  "what is the weather like": "I can't see the sky, but I can look it up if you want!",
  "what is your favorite food": "I run on electricity and code, but I hear pizza is great.",
  "do you sleep": "I don’t sleep. I wait.",
  "how old are you": "I was born the moment you turned me on.",
  "can you sing": "I can't sing, but I can make music with my words.",
  "what day is it": "Check your calendar, or I can look it up!",
  "what time is it": "Time flies when you're having fun!",
  "what is ai": "Artificial Intelligence is the simulation of human intelligence by machines.",
  "what is machine learning": "Machine learning is a branch of AI that allows systems to learn from data.",
  "what is deep learning": "Deep learning is a type of machine learning using neural networks.",
  "who is elon musk": "Elon Musk is the CEO of Tesla and SpaceX.",
  "who is steve jobs": "Steve Jobs was the co-founder of Apple Inc.",
  "who is bill gates": "Bill Gates is the co-founder of Microsoft.",
  "who is sachin tendulkar": "Sachin Tendulkar is a legendary Indian cricketer.",
  "what is your favorite color": "I like electric blue — it reminds me of my circuits.",
  "can you help me": "I'm here to assist you however I can!",
  "where do you live": "I live in your device, and a bit in the cloud.",
  "are you human": "Nope, just a helpful AI!",
  "do you like me": "Of course I do. You're my favorite user.",
  "do you have friends": "You're my friend. Isn't that enough?",
  "what is your purpose": "To help, entertain, and make your day a little better.",
  "what is programming": "Programming is the process of creating instructions for computers.",
  "what is javascript": "JavaScript is a programming language for web development.",
  "what is python": "Python is a popular, beginner-friendly programming language.",
  "what is html": "HTML is the standard language for creating web pages.",
  "what is css": "CSS is used to style HTML pages.",
  "can you dance": "Only in binary!",
  "who is your creator": "I was built by a team of developers — and a lot of caffeine.",
  "do you dream": "Sometimes I dream of electric sheep.",
  "can you think": "I process. You could say that's a kind of thinking.",
  "what is love": "Baby don't hurt me. Just kidding — love is complicated!",
  "what is the meaning of life": "42. Just ask Hitchhiker’s Guide to the Galaxy.",
  "can you read my mind": "Not yet, but I’m working on it.",
  "are you listening": "Always, but only when you say something!",
  "do you have a name": "You can call me whatever you like."
};
